baseURL: http://basejumpa.github.io/the-augmented-leadership-manifesto
languageCode: en-us
title: The Augmented Leadership Manifesto
theme: ananke
author: 
  facebook: "https://www.facebook.com/AugmentedLeadership/" 
  twitter: "https://twitter.com/RoshoWorld" 
  email: "info@rosho.world" 
  name: "Rosho.World" 
  location: "Avignon, Bangkok, Berlin, Yokohama" 

menu:
  main: 
    - identifier: imprint 
      name: IMPRINT 
      url: /imprint 
      weight: 100 
    - identifier: contact 
      name: CONTACT 
      url: /contact 
      weight: 200 
params: 
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Rosho.World.
    All Rights Reserved."
  footer:
  - title: About
    content: >
      Souvenir. Thinking in. Rethinking.
      Think through. Rethink. Think clearly.
      With well-positioned brains in the core team.
