baseURL: https://the-augmented-leadership-manifesto.github.io
languageCode: en-us
title: The Augmented Leadership Manifesto
module:
  imports:
  - path: github.com/theNewDynamic/gohugo-theme-ananke
copyright: Robert Hopp, Otmar Jenner

author: 
  name: "Rosho.World" 
  email: "info@rosho.world" 
  location: "Avignon, Bangkok, Yokohama" 

sectionPagesMenu: main

menu:
  main:
    - identifier: 0
      name: STATEMENT
      url: /statement
      weight: 1
  footer:
    - identifier: contact 
      name: CONTACT 
      url: /contact
      weight: 2
    - identifier: imprint 
      name: IMPRINT 
      url: /imprint
      weight: 3

params:
  toc: true
  ananke_socials:
  - name: linkedin
    url: https://www.linkedin.com/company/68224810
  - name: facebook
    url: https://www.facebook.com/AugmentedLeadership/
  - name: twitter
    url: https://twitter.com/RoshoWorld
