baseURL: https://the-augmented-leadership-manifesto.github.io
languageCode: en-us
title: The Augmented Leadership Manifesto
theme: ananke
author: 
  name: "Rosho.World" 
  email: "info@rosho.world" 
  location: "Avignon, Bangkok, Berlin, Yokohama" 

menu:
  main:
    - identifier: 0
      name: 0
      url: /0
      weight: 1
    - identifier: 1
      name: 1
      url: /1
      weight: 2
    - identifier: 2
      name: 2
      url: /2
      weight: 3
    - identifier: 3
      name: 3
      url: /3
      weight: 4
    - identifier: 4
      name: 4
      url: /4
      weight: 5
    - identifier: 5
      name: 5
      url: /5
      weight: 6
    - identifier: 6
      name: 6
      url: /6
      weight: 7
    - identifier: 7
      name: 7
      url: /7
      weight: 8
    - identifier: 8
      name: 8
      url: /8
      weight: 9
    - identifier: 9
      name: 9
      url: /9
      weight: 10
    - identifier: 10
      name: 10
      url: /10
      weight: 11
    - identifier: 11
      name: 11
      url: /11
      weight: 12
    - identifier: 12
      name: 12
      url: /12
      weight: 13
    - identifier: imprint 
      name: IMPRINT 
      url: /imprint
      weight: 14
    - identifier: contact 
      name: CONTACT 
      url: /contact
      weight: 15
params: 
  ananke_socials:
  - name: linkedin
    url: https://www.linkedin.com/company/68224810
  - name: facebook
    url: https://www.facebook.com/AugmentedLeadership/
  - name: twitter
    url: https://twitter.com/RoshoWorld
